// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module aes_process_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_text_V_AWVALID,
        m_axi_text_V_AWREADY,
        m_axi_text_V_AWADDR,
        m_axi_text_V_AWID,
        m_axi_text_V_AWLEN,
        m_axi_text_V_AWSIZE,
        m_axi_text_V_AWBURST,
        m_axi_text_V_AWLOCK,
        m_axi_text_V_AWCACHE,
        m_axi_text_V_AWPROT,
        m_axi_text_V_AWQOS,
        m_axi_text_V_AWREGION,
        m_axi_text_V_AWUSER,
        m_axi_text_V_WVALID,
        m_axi_text_V_WREADY,
        m_axi_text_V_WDATA,
        m_axi_text_V_WSTRB,
        m_axi_text_V_WLAST,
        m_axi_text_V_WID,
        m_axi_text_V_WUSER,
        m_axi_text_V_ARVALID,
        m_axi_text_V_ARREADY,
        m_axi_text_V_ARADDR,
        m_axi_text_V_ARID,
        m_axi_text_V_ARLEN,
        m_axi_text_V_ARSIZE,
        m_axi_text_V_ARBURST,
        m_axi_text_V_ARLOCK,
        m_axi_text_V_ARCACHE,
        m_axi_text_V_ARPROT,
        m_axi_text_V_ARQOS,
        m_axi_text_V_ARREGION,
        m_axi_text_V_ARUSER,
        m_axi_text_V_RVALID,
        m_axi_text_V_RREADY,
        m_axi_text_V_RDATA,
        m_axi_text_V_RLAST,
        m_axi_text_V_RID,
        m_axi_text_V_RUSER,
        m_axi_text_V_RRESP,
        m_axi_text_V_BVALID,
        m_axi_text_V_BREADY,
        m_axi_text_V_BRESP,
        m_axi_text_V_BID,
        m_axi_text_V_BUSER,
        text_V_offset,
        expanded_key_V_address0,
        expanded_key_V_ce0,
        expanded_key_V_q0,
        s_boxes_V_address0,
        s_boxes_V_ce0,
        s_boxes_V_q0,
        mix_column_constant_matrices_0_V_address0,
        mix_column_constant_matrices_0_V_ce0,
        mix_column_constant_matrices_0_V_q0,
        mix_column_constant_matrices_1_V_address0,
        mix_column_constant_matrices_1_V_ce0,
        mix_column_constant_matrices_1_V_q0,
        mix_column_constant_matrices_2_V_address0,
        mix_column_constant_matrices_2_V_ce0,
        mix_column_constant_matrices_2_V_q0,
        mix_column_constant_matrices_3_V_address0,
        mix_column_constant_matrices_3_V_ce0,
        mix_column_constant_matrices_3_V_q0,
        multiplication_V_address0,
        multiplication_V_ce0,
        multiplication_V_q0,
        multiplication_V_address1,
        multiplication_V_ce1,
        multiplication_V_q1,
        sequence_out_V_address0,
        sequence_out_V_ce0,
        sequence_out_V_we0,
        sequence_out_V_d0
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_text_V_AWVALID;
input   m_axi_text_V_AWREADY;
output  [31:0] m_axi_text_V_AWADDR;
output  [0:0] m_axi_text_V_AWID;
output  [31:0] m_axi_text_V_AWLEN;
output  [2:0] m_axi_text_V_AWSIZE;
output  [1:0] m_axi_text_V_AWBURST;
output  [1:0] m_axi_text_V_AWLOCK;
output  [3:0] m_axi_text_V_AWCACHE;
output  [2:0] m_axi_text_V_AWPROT;
output  [3:0] m_axi_text_V_AWQOS;
output  [3:0] m_axi_text_V_AWREGION;
output  [0:0] m_axi_text_V_AWUSER;
output   m_axi_text_V_WVALID;
input   m_axi_text_V_WREADY;
output  [15:0] m_axi_text_V_WDATA;
output  [1:0] m_axi_text_V_WSTRB;
output   m_axi_text_V_WLAST;
output  [0:0] m_axi_text_V_WID;
output  [0:0] m_axi_text_V_WUSER;
output   m_axi_text_V_ARVALID;
input   m_axi_text_V_ARREADY;
output  [31:0] m_axi_text_V_ARADDR;
output  [0:0] m_axi_text_V_ARID;
output  [31:0] m_axi_text_V_ARLEN;
output  [2:0] m_axi_text_V_ARSIZE;
output  [1:0] m_axi_text_V_ARBURST;
output  [1:0] m_axi_text_V_ARLOCK;
output  [3:0] m_axi_text_V_ARCACHE;
output  [2:0] m_axi_text_V_ARPROT;
output  [3:0] m_axi_text_V_ARQOS;
output  [3:0] m_axi_text_V_ARREGION;
output  [0:0] m_axi_text_V_ARUSER;
input   m_axi_text_V_RVALID;
output   m_axi_text_V_RREADY;
input  [15:0] m_axi_text_V_RDATA;
input   m_axi_text_V_RLAST;
input  [0:0] m_axi_text_V_RID;
input  [0:0] m_axi_text_V_RUSER;
input  [1:0] m_axi_text_V_RRESP;
input   m_axi_text_V_BVALID;
output   m_axi_text_V_BREADY;
input  [1:0] m_axi_text_V_BRESP;
input  [0:0] m_axi_text_V_BID;
input  [0:0] m_axi_text_V_BUSER;
input  [30:0] text_V_offset;
output  [7:0] expanded_key_V_address0;
output   expanded_key_V_ce0;
input  [15:0] expanded_key_V_q0;
output  [9:0] s_boxes_V_address0;
output   s_boxes_V_ce0;
input  [7:0] s_boxes_V_q0;
output  [3:0] mix_column_constant_matrices_0_V_address0;
output   mix_column_constant_matrices_0_V_ce0;
input  [5:0] mix_column_constant_matrices_0_V_q0;
output  [3:0] mix_column_constant_matrices_1_V_address0;
output   mix_column_constant_matrices_1_V_ce0;
input  [5:0] mix_column_constant_matrices_1_V_q0;
output  [3:0] mix_column_constant_matrices_2_V_address0;
output   mix_column_constant_matrices_2_V_ce0;
input  [5:0] mix_column_constant_matrices_2_V_q0;
output  [3:0] mix_column_constant_matrices_3_V_address0;
output   mix_column_constant_matrices_3_V_ce0;
input  [5:0] mix_column_constant_matrices_3_V_q0;
output  [11:0] multiplication_V_address0;
output   multiplication_V_ce0;
input  [7:0] multiplication_V_q0;
output  [11:0] multiplication_V_address1;
output   multiplication_V_ce1;
input  [7:0] multiplication_V_q1;
output  [3:0] sequence_out_V_address0;
output   sequence_out_V_ce0;
output   sequence_out_V_we0;
output  [15:0] sequence_out_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_text_V_ARVALID;
reg m_axi_text_V_RREADY;
reg expanded_key_V_ce0;
reg s_boxes_V_ce0;
reg sequence_out_V_ce0;
reg sequence_out_V_we0;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_fu_259_p2;
reg   [3:0] i_reg_351;
wire    ap_CS_fsm_state5;
wire   [6:0] zext_ln29_fu_265_p1;
reg   [6:0] zext_ln29_reg_356;
wire   [0:0] icmp_ln24_fu_253_p2;
wire   [3:0] add_ln24_fu_270_p2;
reg   [3:0] add_ln24_reg_361;
wire   [2:0] column_fu_282_p2;
reg   [2:0] column_reg_369;
wire    ap_CS_fsm_state18;
wire   [4:0] i_V_fu_288_p2;
reg   [4:0] i_V_reg_374;
wire   [0:0] icmp_ln242_fu_276_p2;
wire   [5:0] zext_ln244_fu_294_p1;
reg   [5:0] zext_ln244_reg_379;
wire   [2:0] row_fu_304_p2;
reg   [2:0] row_reg_387;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln244_fu_298_p2;
wire   [4:0] add_ln700_fu_337_p2;
wire    ap_CS_fsm_state20;
reg   [3:0] state_matrix_V_address0;
reg    state_matrix_V_ce0;
reg    state_matrix_V_we0;
reg   [15:0] state_matrix_V_d0;
wire   [15:0] state_matrix_V_q0;
reg    state_matrix_V_ce1;
wire   [15:0] state_matrix_V_q1;
reg   [3:0] round_key_V_address0;
reg    round_key_V_ce0;
reg    round_key_V_we0;
wire   [15:0] round_key_V_q0;
wire    grp_aes_shift_rows_fu_193_ap_start;
wire    grp_aes_shift_rows_fu_193_ap_done;
wire    grp_aes_shift_rows_fu_193_ap_idle;
wire    grp_aes_shift_rows_fu_193_ap_ready;
wire   [3:0] grp_aes_shift_rows_fu_193_state_matrix_V_address0;
wire    grp_aes_shift_rows_fu_193_state_matrix_V_ce0;
wire    grp_aes_shift_rows_fu_193_state_matrix_V_we0;
wire   [15:0] grp_aes_shift_rows_fu_193_state_matrix_V_d0;
wire    grp_aes_mix_columns8_fu_200_ap_start;
wire    grp_aes_mix_columns8_fu_200_ap_done;
wire    grp_aes_mix_columns8_fu_200_ap_idle;
wire    grp_aes_mix_columns8_fu_200_ap_ready;
wire   [3:0] grp_aes_mix_columns8_fu_200_state_matrix_V_address0;
wire    grp_aes_mix_columns8_fu_200_state_matrix_V_ce0;
wire    grp_aes_mix_columns8_fu_200_state_matrix_V_we0;
wire   [15:0] grp_aes_mix_columns8_fu_200_state_matrix_V_d0;
wire   [3:0] grp_aes_mix_columns8_fu_200_state_matrix_V_address1;
wire    grp_aes_mix_columns8_fu_200_state_matrix_V_ce1;
wire   [3:0] grp_aes_mix_columns8_fu_200_constant_matrix_0_V_address0;
wire    grp_aes_mix_columns8_fu_200_constant_matrix_0_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_200_constant_matrix_1_V_address0;
wire    grp_aes_mix_columns8_fu_200_constant_matrix_1_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_200_constant_matrix_2_V_address0;
wire    grp_aes_mix_columns8_fu_200_constant_matrix_2_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_200_constant_matrix_3_V_address0;
wire    grp_aes_mix_columns8_fu_200_constant_matrix_3_V_ce0;
wire   [11:0] grp_aes_mix_columns8_fu_200_multiplication_V_address0;
wire    grp_aes_mix_columns8_fu_200_multiplication_V_ce0;
wire   [11:0] grp_aes_mix_columns8_fu_200_multiplication_V_address1;
wire    grp_aes_mix_columns8_fu_200_multiplication_V_ce1;
wire    grp_aes_sequence_to_matr_fu_217_ap_start;
wire    grp_aes_sequence_to_matr_fu_217_ap_done;
wire    grp_aes_sequence_to_matr_fu_217_ap_idle;
wire    grp_aes_sequence_to_matr_fu_217_ap_ready;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWVALID;
wire   [31:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWADDR;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWID;
wire   [31:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWLEN;
wire   [2:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWSIZE;
wire   [1:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWBURST;
wire   [1:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWLOCK;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWCACHE;
wire   [2:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWPROT;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWQOS;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWREGION;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWUSER;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WVALID;
wire   [15:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WDATA;
wire   [1:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WSTRB;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WLAST;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WID;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WUSER;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARVALID;
wire   [31:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARADDR;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARID;
wire   [31:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLEN;
wire   [2:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARSIZE;
wire   [1:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARBURST;
wire   [1:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLOCK;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARCACHE;
wire   [2:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARPROT;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARQOS;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARREGION;
wire   [0:0] grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARUSER;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_RREADY;
wire    grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_BREADY;
wire   [3:0] grp_aes_sequence_to_matr_fu_217_matrix_out_V_address0;
wire    grp_aes_sequence_to_matr_fu_217_matrix_out_V_ce0;
wire    grp_aes_sequence_to_matr_fu_217_matrix_out_V_we0;
wire   [15:0] grp_aes_sequence_to_matr_fu_217_matrix_out_V_d0;
wire    grp_aes_get_round_key5_fu_227_ap_start;
wire    grp_aes_get_round_key5_fu_227_ap_done;
wire    grp_aes_get_round_key5_fu_227_ap_idle;
wire    grp_aes_get_round_key5_fu_227_ap_ready;
reg   [6:0] grp_aes_get_round_key5_fu_227_round;
wire   [7:0] grp_aes_get_round_key5_fu_227_expanded_key_V_address0;
wire    grp_aes_get_round_key5_fu_227_expanded_key_V_ce0;
wire   [3:0] grp_aes_get_round_key5_fu_227_round_key_V_address0;
wire    grp_aes_get_round_key5_fu_227_round_key_V_ce0;
wire    grp_aes_get_round_key5_fu_227_round_key_V_we0;
wire   [15:0] grp_aes_get_round_key5_fu_227_round_key_V_d0;
wire    grp_aes_substitute_bytes_fu_238_ap_start;
wire    grp_aes_substitute_bytes_fu_238_ap_done;
wire    grp_aes_substitute_bytes_fu_238_ap_idle;
wire    grp_aes_substitute_bytes_fu_238_ap_ready;
wire   [3:0] grp_aes_substitute_bytes_fu_238_state_matrix_V_address0;
wire    grp_aes_substitute_bytes_fu_238_state_matrix_V_ce0;
wire    grp_aes_substitute_bytes_fu_238_state_matrix_V_we0;
wire   [15:0] grp_aes_substitute_bytes_fu_238_state_matrix_V_d0;
wire   [9:0] grp_aes_substitute_bytes_fu_238_s_box_V_address0;
wire    grp_aes_substitute_bytes_fu_238_s_box_V_ce0;
wire    grp_aes_add_round_key_fu_247_ap_start;
wire    grp_aes_add_round_key_fu_247_ap_done;
wire    grp_aes_add_round_key_fu_247_ap_idle;
wire    grp_aes_add_round_key_fu_247_ap_ready;
wire   [3:0] grp_aes_add_round_key_fu_247_state_matrix_V_address0;
wire    grp_aes_add_round_key_fu_247_state_matrix_V_ce0;
wire    grp_aes_add_round_key_fu_247_state_matrix_V_we0;
wire   [15:0] grp_aes_add_round_key_fu_247_state_matrix_V_d0;
wire   [3:0] grp_aes_add_round_key_fu_247_round_key_matrix_V_address0;
wire    grp_aes_add_round_key_fu_247_round_key_matrix_V_ce0;
reg   [3:0] phi_ln16_reg_126;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state12;
reg   [3:0] i_0_reg_137;
reg   [4:0] p_04_0_i_reg_148;
wire    ap_CS_fsm_state17;
reg   [2:0] column_0_i_reg_160;
reg   [4:0] p_04_1_i_reg_171;
reg   [2:0] row_0_i_reg_182;
reg    grp_aes_shift_rows_fu_193_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state15;
reg    grp_aes_mix_columns8_fu_200_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_aes_sequence_to_matr_fu_217_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_aes_get_round_key5_fu_227_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state13;
reg    grp_aes_substitute_bytes_fu_238_ap_start_reg;
reg    grp_aes_add_round_key_fu_247_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln180_17_fu_327_p1;
wire   [63:0] zext_ln544_fu_332_p1;
wire   [4:0] tmp_fu_310_p3;
wire   [5:0] zext_ln180_fu_318_p1;
wire   [5:0] add_ln180_fu_322_p2;
reg   [19:0] ap_NS_fsm;
reg    ap_block_state2_on_subcall_done;
reg    ap_block_state6_on_subcall_done;
reg    ap_block_state13_on_subcall_done;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_aes_shift_rows_fu_193_ap_start_reg = 1'b0;
#0 grp_aes_mix_columns8_fu_200_ap_start_reg = 1'b0;
#0 grp_aes_sequence_to_matr_fu_217_ap_start_reg = 1'b0;
#0 grp_aes_get_round_key5_fu_227_ap_start_reg = 1'b0;
#0 grp_aes_substitute_bytes_fu_238_ap_start_reg = 1'b0;
#0 grp_aes_add_round_key_fu_247_ap_start_reg = 1'b0;
end

aes_process_1_stadEe #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
state_matrix_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(state_matrix_V_address0),
    .ce0(state_matrix_V_ce0),
    .we0(state_matrix_V_we0),
    .d0(state_matrix_V_d0),
    .q0(state_matrix_V_q0),
    .address1(grp_aes_mix_columns8_fu_200_state_matrix_V_address1),
    .ce1(state_matrix_V_ce1),
    .q1(state_matrix_V_q1)
);

aes_process_1_roueOg #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
round_key_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(round_key_V_address0),
    .ce0(round_key_V_ce0),
    .we0(round_key_V_we0),
    .d0(grp_aes_get_round_key5_fu_227_round_key_V_d0),
    .q0(round_key_V_q0)
);

aes_shift_rows grp_aes_shift_rows_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_shift_rows_fu_193_ap_start),
    .ap_done(grp_aes_shift_rows_fu_193_ap_done),
    .ap_idle(grp_aes_shift_rows_fu_193_ap_idle),
    .ap_ready(grp_aes_shift_rows_fu_193_ap_ready),
    .state_matrix_V_address0(grp_aes_shift_rows_fu_193_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_shift_rows_fu_193_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_shift_rows_fu_193_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_shift_rows_fu_193_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .round_factor(2'd1)
);

aes_mix_columns8 grp_aes_mix_columns8_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_mix_columns8_fu_200_ap_start),
    .ap_done(grp_aes_mix_columns8_fu_200_ap_done),
    .ap_idle(grp_aes_mix_columns8_fu_200_ap_idle),
    .ap_ready(grp_aes_mix_columns8_fu_200_ap_ready),
    .state_matrix_V_address0(grp_aes_mix_columns8_fu_200_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_mix_columns8_fu_200_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_mix_columns8_fu_200_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_mix_columns8_fu_200_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .state_matrix_V_address1(grp_aes_mix_columns8_fu_200_state_matrix_V_address1),
    .state_matrix_V_ce1(grp_aes_mix_columns8_fu_200_state_matrix_V_ce1),
    .state_matrix_V_q1(state_matrix_V_q1),
    .constant_matrix_0_V_address0(grp_aes_mix_columns8_fu_200_constant_matrix_0_V_address0),
    .constant_matrix_0_V_ce0(grp_aes_mix_columns8_fu_200_constant_matrix_0_V_ce0),
    .constant_matrix_0_V_q0(mix_column_constant_matrices_0_V_q0),
    .constant_matrix_1_V_address0(grp_aes_mix_columns8_fu_200_constant_matrix_1_V_address0),
    .constant_matrix_1_V_ce0(grp_aes_mix_columns8_fu_200_constant_matrix_1_V_ce0),
    .constant_matrix_1_V_q0(mix_column_constant_matrices_1_V_q0),
    .constant_matrix_2_V_address0(grp_aes_mix_columns8_fu_200_constant_matrix_2_V_address0),
    .constant_matrix_2_V_ce0(grp_aes_mix_columns8_fu_200_constant_matrix_2_V_ce0),
    .constant_matrix_2_V_q0(mix_column_constant_matrices_2_V_q0),
    .constant_matrix_3_V_address0(grp_aes_mix_columns8_fu_200_constant_matrix_3_V_address0),
    .constant_matrix_3_V_ce0(grp_aes_mix_columns8_fu_200_constant_matrix_3_V_ce0),
    .constant_matrix_3_V_q0(mix_column_constant_matrices_3_V_q0),
    .constant_matrix_V_offset(2'd1),
    .multiplication_V_address0(grp_aes_mix_columns8_fu_200_multiplication_V_address0),
    .multiplication_V_ce0(grp_aes_mix_columns8_fu_200_multiplication_V_ce0),
    .multiplication_V_q0(multiplication_V_q0),
    .multiplication_V_address1(grp_aes_mix_columns8_fu_200_multiplication_V_address1),
    .multiplication_V_ce1(grp_aes_mix_columns8_fu_200_multiplication_V_ce1),
    .multiplication_V_q1(multiplication_V_q1)
);

aes_sequence_to_matr grp_aes_sequence_to_matr_fu_217(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_sequence_to_matr_fu_217_ap_start),
    .ap_done(grp_aes_sequence_to_matr_fu_217_ap_done),
    .ap_idle(grp_aes_sequence_to_matr_fu_217_ap_idle),
    .ap_ready(grp_aes_sequence_to_matr_fu_217_ap_ready),
    .m_axi_sequence_V_AWVALID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWVALID),
    .m_axi_sequence_V_AWREADY(1'b0),
    .m_axi_sequence_V_AWADDR(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWADDR),
    .m_axi_sequence_V_AWID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWID),
    .m_axi_sequence_V_AWLEN(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWLEN),
    .m_axi_sequence_V_AWSIZE(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWSIZE),
    .m_axi_sequence_V_AWBURST(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWBURST),
    .m_axi_sequence_V_AWLOCK(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWLOCK),
    .m_axi_sequence_V_AWCACHE(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWCACHE),
    .m_axi_sequence_V_AWPROT(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWPROT),
    .m_axi_sequence_V_AWQOS(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWQOS),
    .m_axi_sequence_V_AWREGION(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWREGION),
    .m_axi_sequence_V_AWUSER(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_AWUSER),
    .m_axi_sequence_V_WVALID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WVALID),
    .m_axi_sequence_V_WREADY(1'b0),
    .m_axi_sequence_V_WDATA(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WDATA),
    .m_axi_sequence_V_WSTRB(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WSTRB),
    .m_axi_sequence_V_WLAST(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WLAST),
    .m_axi_sequence_V_WID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WID),
    .m_axi_sequence_V_WUSER(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_WUSER),
    .m_axi_sequence_V_ARVALID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARVALID),
    .m_axi_sequence_V_ARREADY(m_axi_text_V_ARREADY),
    .m_axi_sequence_V_ARADDR(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARADDR),
    .m_axi_sequence_V_ARID(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARID),
    .m_axi_sequence_V_ARLEN(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLEN),
    .m_axi_sequence_V_ARSIZE(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARSIZE),
    .m_axi_sequence_V_ARBURST(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARBURST),
    .m_axi_sequence_V_ARLOCK(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLOCK),
    .m_axi_sequence_V_ARCACHE(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARCACHE),
    .m_axi_sequence_V_ARPROT(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARPROT),
    .m_axi_sequence_V_ARQOS(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARQOS),
    .m_axi_sequence_V_ARREGION(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARREGION),
    .m_axi_sequence_V_ARUSER(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARUSER),
    .m_axi_sequence_V_RVALID(m_axi_text_V_RVALID),
    .m_axi_sequence_V_RREADY(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_RREADY),
    .m_axi_sequence_V_RDATA(m_axi_text_V_RDATA),
    .m_axi_sequence_V_RLAST(m_axi_text_V_RLAST),
    .m_axi_sequence_V_RID(m_axi_text_V_RID),
    .m_axi_sequence_V_RUSER(m_axi_text_V_RUSER),
    .m_axi_sequence_V_RRESP(m_axi_text_V_RRESP),
    .m_axi_sequence_V_BVALID(1'b0),
    .m_axi_sequence_V_BREADY(grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_BREADY),
    .m_axi_sequence_V_BRESP(2'd0),
    .m_axi_sequence_V_BID(1'd0),
    .m_axi_sequence_V_BUSER(1'd0),
    .sequence_V_offset(text_V_offset),
    .matrix_out_V_address0(grp_aes_sequence_to_matr_fu_217_matrix_out_V_address0),
    .matrix_out_V_ce0(grp_aes_sequence_to_matr_fu_217_matrix_out_V_ce0),
    .matrix_out_V_we0(grp_aes_sequence_to_matr_fu_217_matrix_out_V_we0),
    .matrix_out_V_d0(grp_aes_sequence_to_matr_fu_217_matrix_out_V_d0)
);

aes_get_round_key5 grp_aes_get_round_key5_fu_227(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_get_round_key5_fu_227_ap_start),
    .ap_done(grp_aes_get_round_key5_fu_227_ap_done),
    .ap_idle(grp_aes_get_round_key5_fu_227_ap_idle),
    .ap_ready(grp_aes_get_round_key5_fu_227_ap_ready),
    .round(grp_aes_get_round_key5_fu_227_round),
    .expanded_key_V_address0(grp_aes_get_round_key5_fu_227_expanded_key_V_address0),
    .expanded_key_V_ce0(grp_aes_get_round_key5_fu_227_expanded_key_V_ce0),
    .expanded_key_V_q0(expanded_key_V_q0),
    .round_key_V_address0(grp_aes_get_round_key5_fu_227_round_key_V_address0),
    .round_key_V_ce0(grp_aes_get_round_key5_fu_227_round_key_V_ce0),
    .round_key_V_we0(grp_aes_get_round_key5_fu_227_round_key_V_we0),
    .round_key_V_d0(grp_aes_get_round_key5_fu_227_round_key_V_d0)
);

aes_substitute_bytes grp_aes_substitute_bytes_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_substitute_bytes_fu_238_ap_start),
    .ap_done(grp_aes_substitute_bytes_fu_238_ap_done),
    .ap_idle(grp_aes_substitute_bytes_fu_238_ap_idle),
    .ap_ready(grp_aes_substitute_bytes_fu_238_ap_ready),
    .state_matrix_V_address0(grp_aes_substitute_bytes_fu_238_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_substitute_bytes_fu_238_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_substitute_bytes_fu_238_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_substitute_bytes_fu_238_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .s_box_V_address0(grp_aes_substitute_bytes_fu_238_s_box_V_address0),
    .s_box_V_ce0(grp_aes_substitute_bytes_fu_238_s_box_V_ce0),
    .s_box_V_q0(s_boxes_V_q0),
    .s_box_V_offset(2'd1)
);

aes_add_round_key grp_aes_add_round_key_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_add_round_key_fu_247_ap_start),
    .ap_done(grp_aes_add_round_key_fu_247_ap_done),
    .ap_idle(grp_aes_add_round_key_fu_247_ap_idle),
    .ap_ready(grp_aes_add_round_key_fu_247_ap_ready),
    .state_matrix_V_address0(grp_aes_add_round_key_fu_247_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_add_round_key_fu_247_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_add_round_key_fu_247_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_add_round_key_fu_247_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .round_key_matrix_V_address0(grp_aes_add_round_key_fu_247_round_key_matrix_V_address0),
    .round_key_matrix_V_ce0(grp_aes_add_round_key_fu_247_round_key_matrix_V_ce0),
    .round_key_matrix_V_q0(round_key_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_add_round_key_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_aes_add_round_key_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_aes_add_round_key_fu_247_ap_ready == 1'b1)) begin
            grp_aes_add_round_key_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_get_round_key5_fu_227_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln24_fu_253_p2 == 1'd1)) | ((icmp_ln24_fu_253_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
            grp_aes_get_round_key5_fu_227_ap_start_reg <= 1'b1;
        end else if ((grp_aes_get_round_key5_fu_227_ap_ready == 1'b1)) begin
            grp_aes_get_round_key5_fu_227_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_mix_columns8_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_aes_mix_columns8_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_aes_mix_columns8_fu_200_ap_ready == 1'b1)) begin
            grp_aes_mix_columns8_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_sequence_to_matr_fu_217_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_aes_sequence_to_matr_fu_217_ap_start_reg <= 1'b1;
        end else if ((grp_aes_sequence_to_matr_fu_217_ap_ready == 1'b1)) begin
            grp_aes_sequence_to_matr_fu_217_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_shift_rows_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state7))) begin
            grp_aes_shift_rows_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_aes_shift_rows_fu_193_ap_ready == 1'b1)) begin
            grp_aes_shift_rows_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_substitute_bytes_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state5) & (icmp_ln24_fu_253_p2 == 1'd1)) | ((icmp_ln24_fu_253_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
            grp_aes_substitute_bytes_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_aes_substitute_bytes_fu_238_ap_ready == 1'b1)) begin
            grp_aes_substitute_bytes_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln244_fu_298_p2 == 1'd1))) begin
        column_0_i_reg_160 <= column_reg_369;
    end else if (((grp_aes_add_round_key_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        column_0_i_reg_160 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_aes_add_round_key_fu_247_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            i_0_reg_137 <= i_reg_351;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            i_0_reg_137 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln244_fu_298_p2 == 1'd1))) begin
        p_04_0_i_reg_148 <= i_V_reg_374;
    end else if (((grp_aes_add_round_key_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        p_04_0_i_reg_148 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        p_04_1_i_reg_171 <= add_ln700_fu_337_p2;
    end else if (((icmp_ln242_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        p_04_1_i_reg_171 <= p_04_0_i_reg_148;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_aes_add_round_key_fu_247_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            phi_ln16_reg_126 <= add_ln24_reg_361;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            phi_ln16_reg_126 <= 4'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        row_0_i_reg_182 <= row_reg_387;
    end else if (((icmp_ln242_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        row_0_i_reg_182 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_253_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        add_ln24_reg_361 <= add_ln24_fu_270_p2;
        zext_ln29_reg_356[3 : 0] <= zext_ln29_fu_265_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        column_reg_369 <= column_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln242_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        i_V_reg_374 <= i_V_fu_288_p2;
        zext_ln244_reg_379[2 : 0] <= zext_ln244_fu_294_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_351 <= i_fu_259_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        row_reg_387 <= row_fu_304_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state18) & (icmp_ln242_fu_276_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln242_fu_276_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2))) begin
        expanded_key_V_ce0 = grp_aes_get_round_key5_fu_227_expanded_key_V_ce0;
    end else begin
        expanded_key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_aes_get_round_key5_fu_227_round = 7'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_aes_get_round_key5_fu_227_round = zext_ln29_reg_356;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_aes_get_round_key5_fu_227_round = 7'd0;
    end else begin
        grp_aes_get_round_key5_fu_227_round = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_text_V_ARVALID = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARVALID;
    end else begin
        m_axi_text_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_text_V_RREADY = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_RREADY;
    end else begin
        m_axi_text_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        round_key_V_address0 = grp_aes_add_round_key_fu_247_round_key_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2))) begin
        round_key_V_address0 = grp_aes_get_round_key5_fu_227_round_key_V_address0;
    end else begin
        round_key_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        round_key_V_ce0 = grp_aes_add_round_key_fu_247_round_key_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2))) begin
        round_key_V_ce0 = grp_aes_get_round_key5_fu_227_round_key_V_ce0;
    end else begin
        round_key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2))) begin
        round_key_V_we0 = grp_aes_get_round_key5_fu_227_round_key_V_we0;
    end else begin
        round_key_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        s_boxes_V_ce0 = grp_aes_substitute_bytes_fu_238_s_box_V_ce0;
    end else begin
        s_boxes_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sequence_out_V_ce0 = 1'b1;
    end else begin
        sequence_out_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sequence_out_V_we0 = 1'b1;
    end else begin
        sequence_out_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        state_matrix_V_address0 = zext_ln180_17_fu_327_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        state_matrix_V_address0 = grp_aes_add_round_key_fu_247_state_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        state_matrix_V_address0 = grp_aes_substitute_bytes_fu_238_state_matrix_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_matrix_V_address0 = grp_aes_sequence_to_matr_fu_217_matrix_out_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_matrix_V_address0 = grp_aes_mix_columns8_fu_200_state_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state8))) begin
        state_matrix_V_address0 = grp_aes_shift_rows_fu_193_state_matrix_V_address0;
    end else begin
        state_matrix_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        state_matrix_V_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        state_matrix_V_ce0 = grp_aes_add_round_key_fu_247_state_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        state_matrix_V_ce0 = grp_aes_substitute_bytes_fu_238_state_matrix_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_matrix_V_ce0 = grp_aes_sequence_to_matr_fu_217_matrix_out_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_matrix_V_ce0 = grp_aes_mix_columns8_fu_200_state_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state8))) begin
        state_matrix_V_ce0 = grp_aes_shift_rows_fu_193_state_matrix_V_ce0;
    end else begin
        state_matrix_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        state_matrix_V_ce1 = grp_aes_mix_columns8_fu_200_state_matrix_V_ce1;
    end else begin
        state_matrix_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        state_matrix_V_d0 = grp_aes_add_round_key_fu_247_state_matrix_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        state_matrix_V_d0 = grp_aes_substitute_bytes_fu_238_state_matrix_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_matrix_V_d0 = grp_aes_sequence_to_matr_fu_217_matrix_out_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_matrix_V_d0 = grp_aes_mix_columns8_fu_200_state_matrix_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state8))) begin
        state_matrix_V_d0 = grp_aes_shift_rows_fu_193_state_matrix_V_d0;
    end else begin
        state_matrix_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4))) begin
        state_matrix_V_we0 = grp_aes_add_round_key_fu_247_state_matrix_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state6))) begin
        state_matrix_V_we0 = grp_aes_substitute_bytes_fu_238_state_matrix_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_matrix_V_we0 = grp_aes_sequence_to_matr_fu_217_matrix_out_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_matrix_V_we0 = grp_aes_mix_columns8_fu_200_state_matrix_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state8))) begin
        state_matrix_V_we0 = grp_aes_shift_rows_fu_193_state_matrix_V_we0;
    end else begin
        state_matrix_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_aes_add_round_key_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln24_fu_253_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_aes_shift_rows_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_aes_mix_columns8_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_aes_add_round_key_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_aes_shift_rows_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_aes_add_round_key_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln242_fu_276_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln244_fu_298_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln180_fu_322_p2 = (zext_ln244_reg_379 + zext_ln180_fu_318_p1);

assign add_ln24_fu_270_p2 = (phi_ln16_reg_126 + 4'd1);

assign add_ln700_fu_337_p2 = (p_04_1_i_reg_171 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13_on_subcall_done = ((grp_aes_substitute_bytes_fu_238_ap_done == 1'b0) | (grp_aes_get_round_key5_fu_227_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_aes_get_round_key5_fu_227_ap_done == 1'b0) | (grp_aes_sequence_to_matr_fu_217_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_aes_substitute_bytes_fu_238_ap_done == 1'b0) | (grp_aes_get_round_key5_fu_227_ap_done == 1'b0));
end

assign column_fu_282_p2 = (column_0_i_reg_160 + 3'd1);

assign expanded_key_V_address0 = grp_aes_get_round_key5_fu_227_expanded_key_V_address0;

assign grp_aes_add_round_key_fu_247_ap_start = grp_aes_add_round_key_fu_247_ap_start_reg;

assign grp_aes_get_round_key5_fu_227_ap_start = grp_aes_get_round_key5_fu_227_ap_start_reg;

assign grp_aes_mix_columns8_fu_200_ap_start = grp_aes_mix_columns8_fu_200_ap_start_reg;

assign grp_aes_sequence_to_matr_fu_217_ap_start = grp_aes_sequence_to_matr_fu_217_ap_start_reg;

assign grp_aes_shift_rows_fu_193_ap_start = grp_aes_shift_rows_fu_193_ap_start_reg;

assign grp_aes_substitute_bytes_fu_238_ap_start = grp_aes_substitute_bytes_fu_238_ap_start_reg;

assign i_V_fu_288_p2 = (p_04_0_i_reg_148 + 5'd4);

assign i_fu_259_p2 = (i_0_reg_137 + 4'd1);

assign icmp_ln242_fu_276_p2 = ((column_0_i_reg_160 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_298_p2 = ((row_0_i_reg_182 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_253_p2 = ((i_0_reg_137 == 4'd13) ? 1'b1 : 1'b0);

assign m_axi_text_V_ARADDR = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARADDR;

assign m_axi_text_V_ARBURST = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARBURST;

assign m_axi_text_V_ARCACHE = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARCACHE;

assign m_axi_text_V_ARID = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARID;

assign m_axi_text_V_ARLEN = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLEN;

assign m_axi_text_V_ARLOCK = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARLOCK;

assign m_axi_text_V_ARPROT = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARPROT;

assign m_axi_text_V_ARQOS = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARQOS;

assign m_axi_text_V_ARREGION = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARREGION;

assign m_axi_text_V_ARSIZE = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARSIZE;

assign m_axi_text_V_ARUSER = grp_aes_sequence_to_matr_fu_217_m_axi_sequence_V_ARUSER;

assign m_axi_text_V_AWADDR = 32'd0;

assign m_axi_text_V_AWBURST = 2'd0;

assign m_axi_text_V_AWCACHE = 4'd0;

assign m_axi_text_V_AWID = 1'd0;

assign m_axi_text_V_AWLEN = 32'd0;

assign m_axi_text_V_AWLOCK = 2'd0;

assign m_axi_text_V_AWPROT = 3'd0;

assign m_axi_text_V_AWQOS = 4'd0;

assign m_axi_text_V_AWREGION = 4'd0;

assign m_axi_text_V_AWSIZE = 3'd0;

assign m_axi_text_V_AWUSER = 1'd0;

assign m_axi_text_V_AWVALID = 1'b0;

assign m_axi_text_V_BREADY = 1'b0;

assign m_axi_text_V_WDATA = 16'd0;

assign m_axi_text_V_WID = 1'd0;

assign m_axi_text_V_WLAST = 1'b0;

assign m_axi_text_V_WSTRB = 2'd0;

assign m_axi_text_V_WUSER = 1'd0;

assign m_axi_text_V_WVALID = 1'b0;

assign mix_column_constant_matrices_0_V_address0 = grp_aes_mix_columns8_fu_200_constant_matrix_0_V_address0;

assign mix_column_constant_matrices_0_V_ce0 = grp_aes_mix_columns8_fu_200_constant_matrix_0_V_ce0;

assign mix_column_constant_matrices_1_V_address0 = grp_aes_mix_columns8_fu_200_constant_matrix_1_V_address0;

assign mix_column_constant_matrices_1_V_ce0 = grp_aes_mix_columns8_fu_200_constant_matrix_1_V_ce0;

assign mix_column_constant_matrices_2_V_address0 = grp_aes_mix_columns8_fu_200_constant_matrix_2_V_address0;

assign mix_column_constant_matrices_2_V_ce0 = grp_aes_mix_columns8_fu_200_constant_matrix_2_V_ce0;

assign mix_column_constant_matrices_3_V_address0 = grp_aes_mix_columns8_fu_200_constant_matrix_3_V_address0;

assign mix_column_constant_matrices_3_V_ce0 = grp_aes_mix_columns8_fu_200_constant_matrix_3_V_ce0;

assign multiplication_V_address0 = grp_aes_mix_columns8_fu_200_multiplication_V_address0;

assign multiplication_V_address1 = grp_aes_mix_columns8_fu_200_multiplication_V_address1;

assign multiplication_V_ce0 = grp_aes_mix_columns8_fu_200_multiplication_V_ce0;

assign multiplication_V_ce1 = grp_aes_mix_columns8_fu_200_multiplication_V_ce1;

assign row_fu_304_p2 = (row_0_i_reg_182 + 3'd1);

assign s_boxes_V_address0 = grp_aes_substitute_bytes_fu_238_s_box_V_address0;

assign sequence_out_V_address0 = zext_ln544_fu_332_p1;

assign sequence_out_V_d0 = state_matrix_V_q0;

assign tmp_fu_310_p3 = {{row_0_i_reg_182}, {2'd0}};

assign zext_ln180_17_fu_327_p1 = add_ln180_fu_322_p2;

assign zext_ln180_fu_318_p1 = tmp_fu_310_p3;

assign zext_ln244_fu_294_p1 = column_0_i_reg_160;

assign zext_ln29_fu_265_p1 = phi_ln16_reg_126;

assign zext_ln544_fu_332_p1 = p_04_1_i_reg_171;

always @ (posedge ap_clk) begin
    zext_ln29_reg_356[6:4] <= 3'b000;
    zext_ln244_reg_379[5:3] <= 3'b000;
end

endmodule //aes_process_1
