// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module aes_process_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        text_V_address0,
        text_V_ce0,
        text_V_we0,
        text_V_d0,
        text_V_q0,
        sequence_out_V_offset,
        initial_round,
        round_factor,
        expanded_key_V_address0,
        expanded_key_V_ce0,
        expanded_key_V_q0,
        s_boxes_V_address0,
        s_boxes_V_ce0,
        s_boxes_V_q0,
        mix_column_constant_matrices_0_V_address0,
        mix_column_constant_matrices_0_V_ce0,
        mix_column_constant_matrices_0_V_q0,
        mix_column_constant_matrices_1_V_address0,
        mix_column_constant_matrices_1_V_ce0,
        mix_column_constant_matrices_1_V_q0,
        mix_column_constant_matrices_2_V_address0,
        mix_column_constant_matrices_2_V_ce0,
        mix_column_constant_matrices_2_V_q0,
        mix_column_constant_matrices_3_V_address0,
        mix_column_constant_matrices_3_V_ce0,
        mix_column_constant_matrices_3_V_q0,
        multiplication_V_address0,
        multiplication_V_ce0,
        multiplication_V_q0,
        multiplication_V_address1,
        multiplication_V_ce1,
        multiplication_V_q1
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] text_V_address0;
output   text_V_ce0;
output   text_V_we0;
output  [15:0] text_V_d0;
input  [15:0] text_V_q0;
input  [5:0] sequence_out_V_offset;
input  [5:0] initial_round;
input  [1:0] round_factor;
output  [7:0] expanded_key_V_address0;
output   expanded_key_V_ce0;
input  [15:0] expanded_key_V_q0;
output  [9:0] s_boxes_V_address0;
output   s_boxes_V_ce0;
input  [7:0] s_boxes_V_q0;
output  [3:0] mix_column_constant_matrices_0_V_address0;
output   mix_column_constant_matrices_0_V_ce0;
input  [5:0] mix_column_constant_matrices_0_V_q0;
output  [3:0] mix_column_constant_matrices_1_V_address0;
output   mix_column_constant_matrices_1_V_ce0;
input  [5:0] mix_column_constant_matrices_1_V_q0;
output  [3:0] mix_column_constant_matrices_2_V_address0;
output   mix_column_constant_matrices_2_V_ce0;
input  [5:0] mix_column_constant_matrices_2_V_q0;
output  [3:0] mix_column_constant_matrices_3_V_address0;
output   mix_column_constant_matrices_3_V_ce0;
input  [5:0] mix_column_constant_matrices_3_V_q0;
output  [11:0] multiplication_V_address0;
output   multiplication_V_ce0;
input  [7:0] multiplication_V_q0;
output  [11:0] multiplication_V_address1;
output   multiplication_V_ce1;
input  [7:0] multiplication_V_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] text_V_address0;
reg text_V_ce0;
reg text_V_we0;
reg expanded_key_V_ce0;
reg s_boxes_V_ce0;
reg mix_column_constant_matrices_0_V_ce0;
reg mix_column_constant_matrices_1_V_ce0;
reg mix_column_constant_matrices_2_V_ce0;
reg mix_column_constant_matrices_3_V_ce0;
reg multiplication_V_ce0;
reg multiplication_V_ce1;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] zext_ln180_cast_fu_290_p1;
reg   [10:0] zext_ln180_cast_reg_552;
wire   [2:0] i_3_fu_300_p2;
reg   [2:0] i_3_reg_560;
wire    ap_CS_fsm_state2;
wire   [5:0] zext_ln230_2_fu_314_p1;
reg   [5:0] zext_ln230_2_reg_565;
wire   [0:0] icmp_ln228_fu_294_p2;
wire   [3:0] zext_ln230_fu_318_p1;
reg   [3:0] zext_ln230_reg_570;
wire   [6:0] zext_ln14_fu_322_p1;
reg   [6:0] zext_ln14_reg_575;
wire   [2:0] j_fu_332_p2;
reg   [2:0] j_reg_584;
wire    ap_CS_fsm_state3;
wire   [5:0] add_ln180_fu_342_p2;
reg   [5:0] add_ln180_reg_589;
wire   [0:0] icmp_ln230_fu_326_p2;
wire   [6:0] round_fu_413_p2;
reg   [6:0] round_reg_599;
wire    ap_CS_fsm_state7;
wire    grp_aes_add_round_key_fu_276_ap_ready;
wire    grp_aes_add_round_key_fu_276_ap_done;
wire   [1:0] select_ln26_fu_418_p3;
reg   [1:0] select_ln26_reg_604;
wire   [0:0] icmp_ln30_fu_426_p2;
reg   [0:0] icmp_ln30_reg_610;
wire  signed [5:0] sext_ln16_fu_431_p1;
reg  signed [5:0] sext_ln16_reg_614;
wire  signed [5:0] add_ln16_fu_434_p2;
reg  signed [5:0] add_ln16_reg_619;
wire    ap_CS_fsm_state8;
wire   [3:0] i_fu_445_p2;
reg   [3:0] i_reg_627;
wire  signed [6:0] sext_ln29_fu_451_p1;
reg  signed [6:0] sext_ln29_reg_632;
wire   [0:0] icmp_ln24_fu_439_p2;
wire   [2:0] column_fu_462_p2;
reg   [2:0] column_reg_640;
wire    ap_CS_fsm_state23;
wire   [4:0] i_V_fu_468_p2;
reg   [4:0] i_V_reg_645;
wire   [0:0] icmp_ln242_fu_456_p2;
wire   [5:0] zext_ln244_fu_474_p1;
reg   [5:0] zext_ln244_reg_650;
wire   [2:0] row_fu_484_p2;
reg   [2:0] row_reg_658;
wire    ap_CS_fsm_state24;
wire   [10:0] add_ln180_5_fu_494_p2;
reg   [10:0] add_ln180_5_reg_663;
wire   [0:0] icmp_ln244_fu_478_p2;
wire   [4:0] add_ln700_fu_521_p2;
reg   [4:0] add_ln700_reg_673;
reg   [3:0] state_matrix_V_address0;
reg    state_matrix_V_ce0;
reg    state_matrix_V_we0;
reg   [15:0] state_matrix_V_d0;
wire   [15:0] state_matrix_V_q0;
reg    state_matrix_V_ce1;
wire   [15:0] state_matrix_V_q1;
reg   [3:0] round_key_V_address0;
reg    round_key_V_ce0;
reg    round_key_V_we0;
reg   [15:0] round_key_V_d0;
wire   [15:0] round_key_V_q0;
reg    round_key_V_ce1;
wire   [15:0] round_key_V_q1;
wire    grp_aes_shift_rows_fu_238_ap_start;
wire    grp_aes_shift_rows_fu_238_ap_done;
wire    grp_aes_shift_rows_fu_238_ap_idle;
wire    grp_aes_shift_rows_fu_238_ap_ready;
wire   [3:0] grp_aes_shift_rows_fu_238_state_matrix_V_address0;
wire    grp_aes_shift_rows_fu_238_state_matrix_V_ce0;
wire    grp_aes_shift_rows_fu_238_state_matrix_V_we0;
wire   [15:0] grp_aes_shift_rows_fu_238_state_matrix_V_d0;
wire    grp_aes_mix_columns8_fu_244_ap_start;
wire    grp_aes_mix_columns8_fu_244_ap_done;
wire    grp_aes_mix_columns8_fu_244_ap_idle;
wire    grp_aes_mix_columns8_fu_244_ap_ready;
wire   [3:0] grp_aes_mix_columns8_fu_244_state_matrix_V_address0;
wire    grp_aes_mix_columns8_fu_244_state_matrix_V_ce0;
wire    grp_aes_mix_columns8_fu_244_state_matrix_V_we0;
wire   [15:0] grp_aes_mix_columns8_fu_244_state_matrix_V_d0;
reg   [15:0] grp_aes_mix_columns8_fu_244_state_matrix_V_q0;
wire   [3:0] grp_aes_mix_columns8_fu_244_state_matrix_V_address1;
wire    grp_aes_mix_columns8_fu_244_state_matrix_V_ce1;
reg   [15:0] grp_aes_mix_columns8_fu_244_state_matrix_V_q1;
wire   [3:0] grp_aes_mix_columns8_fu_244_constant_matrix_0_V_address0;
wire    grp_aes_mix_columns8_fu_244_constant_matrix_0_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_244_constant_matrix_1_V_address0;
wire    grp_aes_mix_columns8_fu_244_constant_matrix_1_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_244_constant_matrix_2_V_address0;
wire    grp_aes_mix_columns8_fu_244_constant_matrix_2_V_ce0;
wire   [3:0] grp_aes_mix_columns8_fu_244_constant_matrix_3_V_address0;
wire    grp_aes_mix_columns8_fu_244_constant_matrix_3_V_ce0;
wire   [11:0] grp_aes_mix_columns8_fu_244_multiplication_V_address0;
wire    grp_aes_mix_columns8_fu_244_multiplication_V_ce0;
wire   [11:0] grp_aes_mix_columns8_fu_244_multiplication_V_address1;
wire    grp_aes_mix_columns8_fu_244_multiplication_V_ce1;
wire    grp_aes_get_round_key5_fu_260_ap_start;
wire    grp_aes_get_round_key5_fu_260_ap_done;
wire    grp_aes_get_round_key5_fu_260_ap_idle;
wire    grp_aes_get_round_key5_fu_260_ap_ready;
reg   [6:0] grp_aes_get_round_key5_fu_260_round;
wire   [7:0] grp_aes_get_round_key5_fu_260_expanded_key_V_address0;
wire    grp_aes_get_round_key5_fu_260_expanded_key_V_ce0;
wire   [3:0] grp_aes_get_round_key5_fu_260_round_key_V_address0;
wire    grp_aes_get_round_key5_fu_260_round_key_V_ce0;
wire    grp_aes_get_round_key5_fu_260_round_key_V_we0;
wire   [15:0] grp_aes_get_round_key5_fu_260_round_key_V_d0;
wire    grp_aes_substitute_bytes_fu_268_ap_start;
wire    grp_aes_substitute_bytes_fu_268_ap_done;
wire    grp_aes_substitute_bytes_fu_268_ap_idle;
wire    grp_aes_substitute_bytes_fu_268_ap_ready;
wire   [3:0] grp_aes_substitute_bytes_fu_268_state_matrix_V_address0;
wire    grp_aes_substitute_bytes_fu_268_state_matrix_V_ce0;
wire    grp_aes_substitute_bytes_fu_268_state_matrix_V_we0;
wire   [15:0] grp_aes_substitute_bytes_fu_268_state_matrix_V_d0;
wire   [9:0] grp_aes_substitute_bytes_fu_268_s_box_V_address0;
wire    grp_aes_substitute_bytes_fu_268_s_box_V_ce0;
wire    grp_aes_add_round_key_fu_276_ap_start;
wire    grp_aes_add_round_key_fu_276_ap_idle;
wire   [3:0] grp_aes_add_round_key_fu_276_state_matrix_V_address0;
wire    grp_aes_add_round_key_fu_276_state_matrix_V_ce0;
wire    grp_aes_add_round_key_fu_276_state_matrix_V_we0;
wire   [15:0] grp_aes_add_round_key_fu_276_state_matrix_V_d0;
wire   [3:0] grp_aes_add_round_key_fu_276_round_key_matrix_V_address0;
wire    grp_aes_add_round_key_fu_276_round_key_matrix_V_ce0;
reg   [2:0] i_op_assign_2_reg_152;
reg   [2:0] i_op_assign_reg_163;
wire    ap_CS_fsm_state4;
reg   [5:0] round_1_reg_174;
wire    ap_CS_fsm_state17;
reg   [3:0] i_0_reg_183;
reg   [4:0] p_04_0_i_reg_194;
wire    ap_CS_fsm_state22;
reg   [2:0] column_0_i_reg_206;
reg   [4:0] p_04_1_i_reg_217;
wire    ap_CS_fsm_state25;
reg   [2:0] row_0_i_reg_227;
reg    grp_aes_shift_rows_fu_238_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state20;
reg    grp_aes_mix_columns8_fu_244_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
reg    grp_aes_get_round_key5_fu_260_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state18;
reg    grp_aes_substitute_bytes_fu_268_ap_start_reg;
reg    grp_aes_add_round_key_fu_276_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state21;
wire   [63:0] zext_ln180_6_fu_371_p1;
wire   [63:0] zext_ln180_12_fu_376_p1;
wire   [63:0] zext_ln180_16_fu_516_p1;
wire   [63:0] zext_ln180_14_fu_527_p1;
wire   [9:0] tmp_fu_282_p3;
wire   [4:0] tmp_9_fu_306_p3;
wire   [5:0] zext_ln180_fu_338_p1;
wire   [1:0] trunc_ln1352_fu_347_p1;
wire   [3:0] ret_V_fu_351_p3;
wire   [3:0] ret_V_3_fu_359_p2;
wire   [9:0] tmp_s_fu_364_p3;
wire  signed [1:0] icmp_ln19_fu_380_p0;
wire  signed [1:0] shl_ln_fu_385_p1;
wire  signed [1:0] shl_ln24_1_fu_392_p1;
wire   [2:0] shl_ln24_1_fu_392_p3;
wire   [5:0] shl_ln_fu_385_p3;
wire  signed [5:0] sext_ln24_fu_399_p1;
wire   [5:0] sub_ln24_fu_403_p2;
wire  signed [6:0] sext_ln24_1_fu_409_p1;
wire   [0:0] icmp_ln19_fu_380_p2;
wire  signed [1:0] icmp_ln30_fu_426_p0;
wire  signed [1:0] sext_ln16_fu_431_p0;
wire   [10:0] zext_ln180_13_fu_490_p1;
wire   [4:0] tmp_1_fu_499_p3;
wire   [5:0] zext_ln180_15_fu_507_p1;
wire   [5:0] add_ln180_6_fu_511_p2;
reg   [24:0] ap_NS_fsm;
reg    ap_block_state9_on_subcall_done;
reg    ap_block_state18_on_subcall_done;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_aes_shift_rows_fu_238_ap_start_reg = 1'b0;
#0 grp_aes_mix_columns8_fu_244_ap_start_reg = 1'b0;
#0 grp_aes_get_round_key5_fu_260_ap_start_reg = 1'b0;
#0 grp_aes_substitute_bytes_fu_268_ap_start_reg = 1'b0;
#0 grp_aes_add_round_key_fu_276_ap_start_reg = 1'b0;
end

aes_process_1_stadEe #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
state_matrix_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(state_matrix_V_address0),
    .ce0(state_matrix_V_ce0),
    .we0(state_matrix_V_we0),
    .d0(state_matrix_V_d0),
    .q0(state_matrix_V_q0),
    .address1(grp_aes_mix_columns8_fu_244_state_matrix_V_address1),
    .ce1(state_matrix_V_ce1),
    .q1(state_matrix_V_q1)
);

aes_process_1_stadEe #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
round_key_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(round_key_V_address0),
    .ce0(round_key_V_ce0),
    .we0(round_key_V_we0),
    .d0(round_key_V_d0),
    .q0(round_key_V_q0),
    .address1(grp_aes_mix_columns8_fu_244_state_matrix_V_address1),
    .ce1(round_key_V_ce1),
    .q1(round_key_V_q1)
);

aes_shift_rows grp_aes_shift_rows_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_shift_rows_fu_238_ap_start),
    .ap_done(grp_aes_shift_rows_fu_238_ap_done),
    .ap_idle(grp_aes_shift_rows_fu_238_ap_idle),
    .ap_ready(grp_aes_shift_rows_fu_238_ap_ready),
    .state_matrix_V_address0(grp_aes_shift_rows_fu_238_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_shift_rows_fu_238_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_shift_rows_fu_238_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_shift_rows_fu_238_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .round_factor(round_factor)
);

aes_mix_columns8 grp_aes_mix_columns8_fu_244(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_mix_columns8_fu_244_ap_start),
    .ap_done(grp_aes_mix_columns8_fu_244_ap_done),
    .ap_idle(grp_aes_mix_columns8_fu_244_ap_idle),
    .ap_ready(grp_aes_mix_columns8_fu_244_ap_ready),
    .state_matrix_V_address0(grp_aes_mix_columns8_fu_244_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_mix_columns8_fu_244_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_mix_columns8_fu_244_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_mix_columns8_fu_244_state_matrix_V_d0),
    .state_matrix_V_q0(grp_aes_mix_columns8_fu_244_state_matrix_V_q0),
    .state_matrix_V_address1(grp_aes_mix_columns8_fu_244_state_matrix_V_address1),
    .state_matrix_V_ce1(grp_aes_mix_columns8_fu_244_state_matrix_V_ce1),
    .state_matrix_V_q1(grp_aes_mix_columns8_fu_244_state_matrix_V_q1),
    .constant_matrix_0_V_address0(grp_aes_mix_columns8_fu_244_constant_matrix_0_V_address0),
    .constant_matrix_0_V_ce0(grp_aes_mix_columns8_fu_244_constant_matrix_0_V_ce0),
    .constant_matrix_0_V_q0(mix_column_constant_matrices_0_V_q0),
    .constant_matrix_1_V_address0(grp_aes_mix_columns8_fu_244_constant_matrix_1_V_address0),
    .constant_matrix_1_V_ce0(grp_aes_mix_columns8_fu_244_constant_matrix_1_V_ce0),
    .constant_matrix_1_V_q0(mix_column_constant_matrices_1_V_q0),
    .constant_matrix_2_V_address0(grp_aes_mix_columns8_fu_244_constant_matrix_2_V_address0),
    .constant_matrix_2_V_ce0(grp_aes_mix_columns8_fu_244_constant_matrix_2_V_ce0),
    .constant_matrix_2_V_q0(mix_column_constant_matrices_2_V_q0),
    .constant_matrix_3_V_address0(grp_aes_mix_columns8_fu_244_constant_matrix_3_V_address0),
    .constant_matrix_3_V_ce0(grp_aes_mix_columns8_fu_244_constant_matrix_3_V_ce0),
    .constant_matrix_3_V_q0(mix_column_constant_matrices_3_V_q0),
    .constant_matrix_V_offset(select_ln26_reg_604),
    .multiplication_V_address0(grp_aes_mix_columns8_fu_244_multiplication_V_address0),
    .multiplication_V_ce0(grp_aes_mix_columns8_fu_244_multiplication_V_ce0),
    .multiplication_V_q0(multiplication_V_q0),
    .multiplication_V_address1(grp_aes_mix_columns8_fu_244_multiplication_V_address1),
    .multiplication_V_ce1(grp_aes_mix_columns8_fu_244_multiplication_V_ce1),
    .multiplication_V_q1(multiplication_V_q1)
);

aes_get_round_key5 grp_aes_get_round_key5_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_get_round_key5_fu_260_ap_start),
    .ap_done(grp_aes_get_round_key5_fu_260_ap_done),
    .ap_idle(grp_aes_get_round_key5_fu_260_ap_idle),
    .ap_ready(grp_aes_get_round_key5_fu_260_ap_ready),
    .round(grp_aes_get_round_key5_fu_260_round),
    .expanded_key_V_address0(grp_aes_get_round_key5_fu_260_expanded_key_V_address0),
    .expanded_key_V_ce0(grp_aes_get_round_key5_fu_260_expanded_key_V_ce0),
    .expanded_key_V_q0(expanded_key_V_q0),
    .round_key_V_address0(grp_aes_get_round_key5_fu_260_round_key_V_address0),
    .round_key_V_ce0(grp_aes_get_round_key5_fu_260_round_key_V_ce0),
    .round_key_V_we0(grp_aes_get_round_key5_fu_260_round_key_V_we0),
    .round_key_V_d0(grp_aes_get_round_key5_fu_260_round_key_V_d0)
);

aes_substitute_bytes grp_aes_substitute_bytes_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_substitute_bytes_fu_268_ap_start),
    .ap_done(grp_aes_substitute_bytes_fu_268_ap_done),
    .ap_idle(grp_aes_substitute_bytes_fu_268_ap_idle),
    .ap_ready(grp_aes_substitute_bytes_fu_268_ap_ready),
    .state_matrix_V_address0(grp_aes_substitute_bytes_fu_268_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_substitute_bytes_fu_268_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_substitute_bytes_fu_268_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_substitute_bytes_fu_268_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .s_box_V_address0(grp_aes_substitute_bytes_fu_268_s_box_V_address0),
    .s_box_V_ce0(grp_aes_substitute_bytes_fu_268_s_box_V_ce0),
    .s_box_V_q0(s_boxes_V_q0),
    .s_box_V_offset(select_ln26_reg_604)
);

aes_add_round_key grp_aes_add_round_key_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_aes_add_round_key_fu_276_ap_start),
    .ap_done(grp_aes_add_round_key_fu_276_ap_done),
    .ap_idle(grp_aes_add_round_key_fu_276_ap_idle),
    .ap_ready(grp_aes_add_round_key_fu_276_ap_ready),
    .state_matrix_V_address0(grp_aes_add_round_key_fu_276_state_matrix_V_address0),
    .state_matrix_V_ce0(grp_aes_add_round_key_fu_276_state_matrix_V_ce0),
    .state_matrix_V_we0(grp_aes_add_round_key_fu_276_state_matrix_V_we0),
    .state_matrix_V_d0(grp_aes_add_round_key_fu_276_state_matrix_V_d0),
    .state_matrix_V_q0(state_matrix_V_q0),
    .round_key_matrix_V_address0(grp_aes_add_round_key_fu_276_round_key_matrix_V_address0),
    .round_key_matrix_V_ce0(grp_aes_add_round_key_fu_276_round_key_matrix_V_ce0),
    .round_key_matrix_V_q0(round_key_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_add_round_key_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state6))) begin
            grp_aes_add_round_key_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_aes_add_round_key_fu_276_ap_ready == 1'b1)) begin
            grp_aes_add_round_key_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_get_round_key5_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_fu_294_p2 == 1'd1)))) begin
            grp_aes_get_round_key5_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_aes_get_round_key5_fu_260_ap_ready == 1'b1)) begin
            grp_aes_get_round_key5_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_mix_columns8_fu_244_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
            grp_aes_mix_columns8_fu_244_ap_start_reg <= 1'b1;
        end else if ((grp_aes_mix_columns8_fu_244_ap_ready == 1'b1)) begin
            grp_aes_mix_columns8_fu_244_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_shift_rows_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state10))) begin
            grp_aes_shift_rows_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_aes_shift_rows_fu_238_ap_ready == 1'b1)) begin
            grp_aes_shift_rows_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_aes_substitute_bytes_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd0)))) begin
            grp_aes_substitute_bytes_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_aes_substitute_bytes_fu_268_ap_ready == 1'b1)) begin
            grp_aes_substitute_bytes_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln244_fu_478_p2 == 1'd1))) begin
        column_0_i_reg_206 <= column_reg_640;
    end else if (((1'b1 == ap_CS_fsm_state22) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
        column_0_i_reg_206 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_aes_add_round_key_fu_276_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            i_0_reg_183 <= i_reg_627;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            i_0_reg_183 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln230_fu_326_p2 == 1'd1))) begin
        i_op_assign_2_reg_152 <= i_3_reg_560;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_op_assign_2_reg_152 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_fu_294_p2 == 1'd0))) begin
        i_op_assign_reg_163 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_op_assign_reg_163 <= j_reg_584;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln244_fu_478_p2 == 1'd1))) begin
        p_04_0_i_reg_194 <= i_V_reg_645;
    end else if (((1'b1 == ap_CS_fsm_state22) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
        p_04_0_i_reg_194 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        p_04_1_i_reg_217 <= add_ln700_reg_673;
    end else if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd0))) begin
        p_04_1_i_reg_217 <= p_04_0_i_reg_194;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_aes_add_round_key_fu_276_ap_done == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            round_1_reg_174 <= add_ln16_reg_619;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            round_1_reg_174 <= initial_round;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        row_0_i_reg_227 <= row_reg_658;
    end else if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd0))) begin
        row_0_i_reg_227 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln16_reg_619 <= add_ln16_fu_434_p2;
        i_reg_627 <= i_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln244_fu_478_p2 == 1'd0))) begin
        add_ln180_5_reg_663 <= add_ln180_5_fu_494_p2;
        add_ln700_reg_673 <= add_ln700_fu_521_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln230_fu_326_p2 == 1'd0))) begin
        add_ln180_reg_589 <= add_ln180_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        column_reg_640 <= column_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_3_reg_560 <= i_3_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd0))) begin
        i_V_reg_645 <= i_V_fu_468_p2;
        zext_ln244_reg_650[2 : 0] <= zext_ln244_fu_474_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
        icmp_ln30_reg_610 <= icmp_ln30_fu_426_p2;
        round_reg_599 <= round_fu_413_p2;
        select_ln26_reg_604 <= select_ln26_fu_418_p3;
        sext_ln16_reg_614 <= sext_ln16_fu_431_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_584 <= j_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        row_reg_658 <= row_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd0))) begin
        sext_ln29_reg_632 <= sext_ln29_fu_451_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_fu_294_p2 == 1'd1))) begin
        zext_ln14_reg_575[5 : 0] <= zext_ln14_fu_322_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        zext_ln180_cast_reg_552[9 : 4] <= zext_ln180_cast_fu_290_p1[9 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_fu_294_p2 == 1'd0))) begin
        zext_ln230_2_reg_565[4 : 2] <= zext_ln230_2_fu_314_p1[4 : 2];
        zext_ln230_reg_570[2 : 0] <= zext_ln230_fu_318_p1[2 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        expanded_key_V_ce0 = grp_aes_get_round_key5_fu_260_expanded_key_V_ce0;
    end else begin
        expanded_key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_aes_get_round_key5_fu_260_round = round_reg_599;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_aes_get_round_key5_fu_260_round = sext_ln29_reg_632;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_aes_get_round_key5_fu_260_round = zext_ln14_reg_575;
    end else begin
        grp_aes_get_round_key5_fu_260_round = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q0 = round_key_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q0 = state_matrix_V_q0;
    end else begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q1 = round_key_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q1 = state_matrix_V_q1;
    end else begin
        grp_aes_mix_columns8_fu_244_state_matrix_V_q1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        mix_column_constant_matrices_0_V_ce0 = grp_aes_mix_columns8_fu_244_constant_matrix_0_V_ce0;
    end else begin
        mix_column_constant_matrices_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        mix_column_constant_matrices_1_V_ce0 = grp_aes_mix_columns8_fu_244_constant_matrix_1_V_ce0;
    end else begin
        mix_column_constant_matrices_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        mix_column_constant_matrices_2_V_ce0 = grp_aes_mix_columns8_fu_244_constant_matrix_2_V_ce0;
    end else begin
        mix_column_constant_matrices_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        mix_column_constant_matrices_3_V_ce0 = grp_aes_mix_columns8_fu_244_constant_matrix_3_V_ce0;
    end else begin
        mix_column_constant_matrices_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        multiplication_V_ce0 = grp_aes_mix_columns8_fu_244_multiplication_V_ce0;
    end else begin
        multiplication_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        multiplication_V_ce1 = grp_aes_mix_columns8_fu_244_multiplication_V_ce1;
    end else begin
        multiplication_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        round_key_V_address0 = grp_aes_add_round_key_fu_276_round_key_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        round_key_V_address0 = grp_aes_get_round_key5_fu_260_round_key_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        round_key_V_address0 = grp_aes_mix_columns8_fu_244_state_matrix_V_address0;
    end else begin
        round_key_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        round_key_V_ce0 = grp_aes_add_round_key_fu_276_round_key_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        round_key_V_ce0 = grp_aes_get_round_key5_fu_260_round_key_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        round_key_V_ce0 = grp_aes_mix_columns8_fu_244_state_matrix_V_ce0;
    end else begin
        round_key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        round_key_V_ce1 = grp_aes_mix_columns8_fu_244_state_matrix_V_ce1;
    end else begin
        round_key_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        round_key_V_d0 = grp_aes_get_round_key5_fu_260_round_key_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        round_key_V_d0 = grp_aes_mix_columns8_fu_244_state_matrix_V_d0;
    end else begin
        round_key_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        round_key_V_we0 = grp_aes_get_round_key5_fu_260_round_key_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        round_key_V_we0 = grp_aes_mix_columns8_fu_244_state_matrix_V_we0;
    end else begin
        round_key_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9))) begin
        s_boxes_V_ce0 = grp_aes_substitute_bytes_fu_268_s_box_V_ce0;
    end else begin
        s_boxes_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        state_matrix_V_address0 = zext_ln180_16_fu_516_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_matrix_V_address0 = zext_ln180_12_fu_376_p1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        state_matrix_V_address0 = grp_aes_add_round_key_fu_276_state_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9))) begin
        state_matrix_V_address0 = grp_aes_substitute_bytes_fu_268_state_matrix_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_matrix_V_address0 = grp_aes_mix_columns8_fu_244_state_matrix_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state11))) begin
        state_matrix_V_address0 = grp_aes_shift_rows_fu_238_state_matrix_V_address0;
    end else begin
        state_matrix_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state24))) begin
        state_matrix_V_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        state_matrix_V_ce0 = grp_aes_add_round_key_fu_276_state_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9))) begin
        state_matrix_V_ce0 = grp_aes_substitute_bytes_fu_268_state_matrix_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_matrix_V_ce0 = grp_aes_mix_columns8_fu_244_state_matrix_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state11))) begin
        state_matrix_V_ce0 = grp_aes_shift_rows_fu_238_state_matrix_V_ce0;
    end else begin
        state_matrix_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        state_matrix_V_ce1 = grp_aes_mix_columns8_fu_244_state_matrix_V_ce1;
    end else begin
        state_matrix_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_matrix_V_d0 = text_V_q0;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        state_matrix_V_d0 = grp_aes_add_round_key_fu_276_state_matrix_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9))) begin
        state_matrix_V_d0 = grp_aes_substitute_bytes_fu_268_state_matrix_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_matrix_V_d0 = grp_aes_mix_columns8_fu_244_state_matrix_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state11))) begin
        state_matrix_V_d0 = grp_aes_shift_rows_fu_238_state_matrix_V_d0;
    end else begin
        state_matrix_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_matrix_V_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7))) begin
        state_matrix_V_we0 = grp_aes_add_round_key_fu_276_state_matrix_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state9))) begin
        state_matrix_V_we0 = grp_aes_substitute_bytes_fu_268_state_matrix_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        state_matrix_V_we0 = grp_aes_mix_columns8_fu_244_state_matrix_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state11))) begin
        state_matrix_V_we0 = grp_aes_shift_rows_fu_238_state_matrix_V_we0;
    end else begin
        state_matrix_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        text_V_address0 = zext_ln180_14_fu_527_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        text_V_address0 = zext_ln180_6_fu_371_p1;
    end else begin
        text_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state3))) begin
        text_V_ce0 = 1'b1;
    end else begin
        text_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        text_V_we0 = 1'b1;
    end else begin
        text_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_fu_294_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln230_fu_326_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_aes_get_round_key5_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln24_fu_439_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_aes_shift_rows_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_aes_mix_columns8_fu_244_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln30_reg_610 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((grp_aes_mix_columns8_fu_244_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln30_reg_610 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_aes_mix_columns8_fu_244_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_aes_shift_rows_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (grp_aes_add_round_key_fu_276_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln242_fu_456_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln244_fu_478_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_434_p2 = ($signed(round_1_reg_174) + $signed(sext_ln16_reg_614));

assign add_ln180_5_fu_494_p2 = (zext_ln180_13_fu_490_p1 + zext_ln180_cast_reg_552);

assign add_ln180_6_fu_511_p2 = (zext_ln244_reg_650 + zext_ln180_15_fu_507_p1);

assign add_ln180_fu_342_p2 = (zext_ln180_fu_338_p1 + zext_ln230_2_reg_565);

assign add_ln700_fu_521_p2 = (p_04_1_i_reg_217 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_on_subcall_done = ((grp_aes_substitute_bytes_fu_268_ap_done == 1'b0) | (grp_aes_get_round_key5_fu_260_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state9_on_subcall_done = ((grp_aes_substitute_bytes_fu_268_ap_done == 1'b0) | (grp_aes_get_round_key5_fu_260_ap_done == 1'b0));
end

assign column_fu_462_p2 = (column_0_i_reg_206 + 3'd1);

assign expanded_key_V_address0 = grp_aes_get_round_key5_fu_260_expanded_key_V_address0;

assign grp_aes_add_round_key_fu_276_ap_start = grp_aes_add_round_key_fu_276_ap_start_reg;

assign grp_aes_get_round_key5_fu_260_ap_start = grp_aes_get_round_key5_fu_260_ap_start_reg;

assign grp_aes_mix_columns8_fu_244_ap_start = grp_aes_mix_columns8_fu_244_ap_start_reg;

assign grp_aes_shift_rows_fu_238_ap_start = grp_aes_shift_rows_fu_238_ap_start_reg;

assign grp_aes_substitute_bytes_fu_268_ap_start = grp_aes_substitute_bytes_fu_268_ap_start_reg;

assign i_3_fu_300_p2 = (i_op_assign_2_reg_152 + 3'd1);

assign i_V_fu_468_p2 = (p_04_0_i_reg_194 + 5'd4);

assign i_fu_445_p2 = (i_0_reg_183 + 4'd1);

assign icmp_ln19_fu_380_p0 = round_factor;

assign icmp_ln19_fu_380_p2 = ((icmp_ln19_fu_380_p0 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln228_fu_294_p2 = ((i_op_assign_2_reg_152 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_326_p2 = ((i_op_assign_reg_163 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln242_fu_456_p2 = ((column_0_i_reg_206 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_478_p2 = ((row_0_i_reg_227 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_439_p2 = ((i_0_reg_183 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_426_p0 = round_factor;

assign icmp_ln30_fu_426_p2 = ((icmp_ln30_fu_426_p0 == 2'd3) ? 1'b1 : 1'b0);

assign j_fu_332_p2 = (i_op_assign_reg_163 + 3'd1);

assign mix_column_constant_matrices_0_V_address0 = grp_aes_mix_columns8_fu_244_constant_matrix_0_V_address0;

assign mix_column_constant_matrices_1_V_address0 = grp_aes_mix_columns8_fu_244_constant_matrix_1_V_address0;

assign mix_column_constant_matrices_2_V_address0 = grp_aes_mix_columns8_fu_244_constant_matrix_2_V_address0;

assign mix_column_constant_matrices_3_V_address0 = grp_aes_mix_columns8_fu_244_constant_matrix_3_V_address0;

assign multiplication_V_address0 = grp_aes_mix_columns8_fu_244_multiplication_V_address0;

assign multiplication_V_address1 = grp_aes_mix_columns8_fu_244_multiplication_V_address1;

assign ret_V_3_fu_359_p2 = (ret_V_fu_351_p3 + zext_ln230_reg_570);

assign ret_V_fu_351_p3 = {{trunc_ln1352_fu_347_p1}, {2'd0}};

assign round_fu_413_p2 = ($signed(sext_ln24_1_fu_409_p1) + $signed(zext_ln14_reg_575));

assign row_fu_484_p2 = (row_0_i_reg_227 + 3'd1);

assign s_boxes_V_address0 = grp_aes_substitute_bytes_fu_268_s_box_V_address0;

assign select_ln26_fu_418_p3 = ((icmp_ln19_fu_380_p2[0:0] === 1'b1) ? 2'd1 : 2'd2);

assign sext_ln16_fu_431_p0 = round_factor;

assign sext_ln16_fu_431_p1 = sext_ln16_fu_431_p0;

assign sext_ln24_1_fu_409_p1 = $signed(sub_ln24_fu_403_p2);

assign sext_ln24_fu_399_p1 = $signed(shl_ln24_1_fu_392_p3);

assign sext_ln29_fu_451_p1 = add_ln16_fu_434_p2;

assign shl_ln24_1_fu_392_p1 = round_factor;

assign shl_ln24_1_fu_392_p3 = {{shl_ln24_1_fu_392_p1}, {1'd0}};

assign shl_ln_fu_385_p1 = round_factor;

assign shl_ln_fu_385_p3 = {{shl_ln_fu_385_p1}, {4'd0}};

assign sub_ln24_fu_403_p2 = ($signed(shl_ln_fu_385_p3) - $signed(sext_ln24_fu_399_p1));

assign text_V_d0 = state_matrix_V_q0;

assign tmp_1_fu_499_p3 = {{row_0_i_reg_227}, {2'd0}};

assign tmp_9_fu_306_p3 = {{i_op_assign_2_reg_152}, {2'd0}};

assign tmp_fu_282_p3 = {{sequence_out_V_offset}, {4'd0}};

assign tmp_s_fu_364_p3 = {{sequence_out_V_offset}, {ret_V_3_fu_359_p2}};

assign trunc_ln1352_fu_347_p1 = i_op_assign_reg_163[1:0];

assign zext_ln14_fu_322_p1 = initial_round;

assign zext_ln180_12_fu_376_p1 = add_ln180_reg_589;

assign zext_ln180_13_fu_490_p1 = p_04_1_i_reg_217;

assign zext_ln180_14_fu_527_p1 = add_ln180_5_reg_663;

assign zext_ln180_15_fu_507_p1 = tmp_1_fu_499_p3;

assign zext_ln180_16_fu_516_p1 = add_ln180_6_fu_511_p2;

assign zext_ln180_6_fu_371_p1 = tmp_s_fu_364_p3;

assign zext_ln180_cast_fu_290_p1 = tmp_fu_282_p3;

assign zext_ln180_fu_338_p1 = i_op_assign_reg_163;

assign zext_ln230_2_fu_314_p1 = tmp_9_fu_306_p3;

assign zext_ln230_fu_318_p1 = i_op_assign_2_reg_152;

assign zext_ln244_fu_474_p1 = column_0_i_reg_206;

always @ (posedge ap_clk) begin
    zext_ln180_cast_reg_552[3:0] <= 4'b0000;
    zext_ln180_cast_reg_552[10] <= 1'b0;
    zext_ln230_2_reg_565[1:0] <= 2'b00;
    zext_ln230_2_reg_565[5] <= 1'b0;
    zext_ln230_reg_570[3] <= 1'b0;
    zext_ln14_reg_575[6] <= 1'b0;
    zext_ln244_reg_650[5:3] <= 3'b000;
end

endmodule //aes_process_2
